(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const icons={overview:'⌂',tb:'▦',map:'◉',rounds:'↻'};
const labels={overview:'الرئيسية',tb:'الميزان',map:'الخريطة',rounds:'الجولات'};
function clickGo(view){const b=$(`.tab[data-go="${view}"]`);if(b){b.click();return true}return false}
function decorateTabs(){const bar=$('#tabbar');if(!bar)return;['overview','tb','map','rounds'].forEach(view=>{const b=$(`.tab[data-go="${view}"]`,bar);if(!b||b.dataset.kosifDone)return;const n=b.querySelector('.n');b.dataset.kosifDone='1';[...b.childNodes].forEach(node=>{if(node.nodeType===3)node.textContent=''});const ic=document.createElement('span');ic.className='tab-icon';ic.textContent=icons[view];const lb=document.createElement('span');lb.className='tab-label';lb.textContent=labels[view];b.prepend(lb);b.prepend(ic);if(n)b.append(n)});if(!$('.kosif-more',bar)){const b=document.createElement('button');b.className='tab kosif-more';b.type='button';b.innerHTML='<span class="tab-icon">☰</span><span class="tab-label">المزيد</span>';b.onclick=()=>openSheet('more');bar.append(b)}}
function addQuickbar(){const inner=$('.topbar-inner');if(!inner||$('.kosif-quickbar',inner))return;const q=document.createElement('div');q.className='kosif-quickbar';q.innerHTML='<button class="kosif-qbtn" data-kq="report">▤ <span>التقرير النهائي</span></button><button class="kosif-qbtn" data-kq="commands">⌘K <span>بحث وأوامر</span></button><button class="kosif-qbtn" data-kq="theme" aria-label="تبديل الوضع">🌙</button><button class="kosif-qbtn library" data-kq="library">📚 <span>المكتبة</span></button>';inner.append(q);$('[data-kq="report"]',q).onclick=()=>clickGo('outputs');$('[data-kq="library"]',q).onclick=()=>location.href='./standards/';$('[data-kq="commands"]',q).onclick=()=>openSheet('commands');$('[data-kq="theme"]',q).onclick=()=>{document.body.classList.toggle('kosif-night');localStorage.setItem('kosif-theme',document.body.classList.contains('kosif-night')?'night':'light');$('[data-kq="theme"]',q).textContent=document.body.classList.contains('kosif-night')?'☀️':'🌙'}}
function makeSheet(){if($('#kosif-sheet-backdrop'))return;const back=document.createElement('div');back.id='kosif-sheet-backdrop';back.className='kosif-sheet-backdrop';back.innerHTML='<div class="kosif-sheet" role="dialog" aria-modal="true"><div class="kosif-sheet-title"></div><div class="kosif-sheet-grid"></div></div>';back.onclick=e=>{if(e.target===back)closeSheet()};document.body.append(back)}
function openSheet(kind){makeSheet();const back=$('#kosif-sheet-backdrop'),title=$('.kosif-sheet-title',back),grid=$('.kosif-sheet-grid',back);if(kind==='more'){title.textContent='المزيد';grid.innerHTML='<button data-v="outputs">▤ المخرجات</button><button class="accent" data-v="library">📚 مكتبة المعايير</button><button data-v="settings">⚙ الإعدادات</button><button data-close>إغلاق</button>'}else{title.textContent='بحث وأوامر';grid.innerHTML='<button class="accent" data-v="overview">⌂ الرئيسية</button><button data-v="tb">▦ ميزان المراجعة</button><button data-v="map">◉ الخريطة المعيارية</button><button data-v="rounds">↻ جولات المراجعة</button><button data-v="outputs">▤ المخرجات</button><button data-v="library">📚 مكتبة المعايير</button><button data-v="settings">⚙ الإعدادات</button><button data-close>إغلاق</button>'}$$('[data-v]',grid).forEach(b=>b.onclick=()=>{const v=b.dataset.v;closeSheet();if(v==='library')location.href='./standards/';else clickGo(v)});$('[data-close]',grid).onclick=closeSheet;back.classList.add('on')}
function closeSheet(){const b=$('#kosif-sheet-backdrop');if(b)b.classList.remove('on')}
function restoreBrand(){const n=$('.brand-name');if(n)n.textContent='Kosif';const sub=$('.brand-sub');if(sub)sub.textContent='منصة المراجعة الذكية متعددة الجولات · تحليلات وأدلة وتقارير · IFRS · SOCPA · ISA'}
function applySavedTheme(){const night=localStorage.getItem('kosif-theme')==='night';document.body.classList.toggle('kosif-night',night);const b=$('[data-kq="theme"]');if(b)b.textContent=night?'☀️':'🌙'}
function init(){restoreBrand();decorateTabs();addQuickbar();makeSheet();applySavedTheme();document.documentElement.dataset.kosifTheme='restored-v1'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();new MutationObserver(()=>{restoreBrand();decorateTabs();addQuickbar()}).observe(document.documentElement,{childList:true,subtree:true});
})();
