import fs from 'node:fs';

const source='frontend/index.html',target='public/index.html';
const cssHref='/kosif-design-system-v44.css',jsSrc='/kosif-design-system-v44.js';
const visualCssHref='/kosif-visual-system-v45.css?v=2026.08.21-2',visualJsSrc='/kosif-visual-system-v45.js?v=2026.08.21-1';
const enterpriseTokensHref='/kosif-enterprise-tokens-v46.css';
const a11yCssHref='/kosif-a11y-v46.css?v=46',a11yJsSrc='/kosif-a11y-v46.js?v=46';
const read=p=>fs.readFileSync(p,'utf8'),write=(p,s)=>fs.writeFileSync(p,s);

function applyVisualSystemV45(s){if(!s.includes('data-kosif-visual-system="v45"'))s=s.replace(/<html\b/,'<html data-kosif-visual-system="v45"');if(!s.includes(visualCssHref))s=s.replace('</head>',`  <link rel="stylesheet" id="kosif-visual-system-v45" href="${visualCssHref}">\n</head>`);if(!s.includes(visualJsSrc))s=s.replace('</head>',`  <script id="kosif-visual-system-v45-guard" src="${visualJsSrc}" defer></script>\n</head>`);return s}
function applyEnterpriseTokensV46(s){if(!s.includes('data-kosif-enterprise-tokens="v46"'))s=s.replace(/<html\b/,'<html data-kosif-enterprise-tokens="v46"');if(!s.includes(enterpriseTokensHref))s=s.replace('</head>',`  <link rel="stylesheet" id="kosif-enterprise-tokens-v46" href="${enterpriseTokensHref}">\n</head>`);return s}
function applyA11yLayerV46(s){if(!s.includes(a11yCssHref))s=s.replace('</head>',`  <link rel="stylesheet" id="kosif-a11y-v46" href="${a11yCssHref}">\n</head>`);if(!s.includes(a11yJsSrc))s=s.replace('</body>',`  <script id="kosif-a11y-v46-runtime" src="${a11yJsSrc}" defer></script>\n</body>`);return s}
function applyAccessibilityV46(s,p){if(p.endsWith('/standards/index.html'))s=s.replace('content="width=device-width,initial-scale=1,viewport-fit=cover,maximum-scale=1"','content="width=device-width,initial-scale=1,viewport-fit=cover"').replace('<input type="range" id="rgFs" min="15" max="30" step="1">','<input type="range" id="rgFs" min="15" max="30" step="1" aria-label="حجم النص">').replace('<input type="range" id="rgLh" min="16" max="26" step="1">','<input type="range" id="rgLh" min="16" max="26" step="1" aria-label="تباعد الأسطر">').replace('<input id="q" type="search" placeholder="اكتب كلمة أو رقم فقرة…" autocomplete="off">','<input id="q" type="search" placeholder="اكتب كلمة أو رقم فقرة…" autocomplete="off" aria-label="بحث في الكتاب">');return s}
function applyAuditCopyV46(s){return s.replace(/<title>kosif<\/title>/i,'<title>KOSIF | مساحة المراجعة</title>').replace(/<meta name="description" content="[^"]*">/i,'<meta name="description" content="KOSIF منصة للمراجعة والامتثال الذكي تربط الأرقام الحتمية بالأدلة والمعايير والمراجعة البشرية.">')}

function applyShellBundleV46(p){if(!fs.existsSync(p))return;let s=read(p);s=s.replace('<link rel="stylesheet" href="/suite.css">','<link rel="stylesheet" href="/bundles/kosif-suite-core-v46.css?v=46">').replace(/\s*<link rel="stylesheet" href="\/suite-shell\.css">/,'');if(p.endsWith('/sales/index.html'))s=s.replace('<link rel="stylesheet" href="/sales/sales.css">','<link rel="stylesheet" href="/sales/sales-ui-v46.css?v=46">').replace(/\s*<link rel="stylesheet" href="\/sales\/sales-motion-v1\.css">/,'').replace(/\s*<script src="\/sales\/sales-general-bootstrap\.js"><\/script>/,'').replaceAll("localStorage.getItem('kosif:aghnam:v7:native')","localStorage.getItem('kosif:sales:v1')");write(p,s)}
function applySalesRuntimeV46(){const p='public/sales/sales.js';if(!fs.existsSync(p))return;let s=read(p);if(s.includes("const STORE='kosif:aghnam:v7:native';"))s=s.replace("const STORE='kosif:aghnam:v7:native';","const STORE='kosif:sales:v1';\nconst LEGACY_STORE='kosif:aghnam:v7:native';\nwindow.__KOSIF_SALES_STORE_KEY__=STORE;");
if(s.includes("meta:{source:'Aghnam v7 native integration'")){const generic=`const sample={sales:[\n{id:'G-1',date:'2026-08-01',product:'المنتج A',category:'منتجات',channel:'المتجر الإلكتروني',qty:18,revenue:12600,cost:8460,customer:'عميل 001',phone:'0500000001',city:'الرياض',payment:'مدى'},\n{id:'G-2',date:'2026-08-02',product:'الخدمة الأساسية',category:'خدمات',channel:'واتساب',qty:14,revenue:9100,cost:5160,customer:'عميل 002',phone:'0500000002',city:'جدة',payment:'تحويل'},\n{id:'G-3',date:'2026-08-03',product:'المنتج B',category:'منتجات',channel:'الفرع',qty:22,revenue:12100,cost:7920,customer:'شركة تجريبية',phone:'0500000003',city:'مكة',payment:'شبكة'},\n{id:'G-4',date:'2026-08-04',product:'الباقة المتقدمة',category:'باقات',channel:'المتجر الإلكتروني',qty:26,revenue:14820,cost:8620,customer:'عميل 004',phone:'0500000004',city:'الدمام',payment:'مدى'}],clients:[],tasks:[],costs:{},meta:{source:'KOSIF general sales demo',designAuthority:'KOSIF Sales workspace v46',updatedAt:new Date().toISOString()}};`;
s=s.replace(/const sample=\{sales:\[[\s\S]*?\],clients:\[\],tasks:\[\],costs:\{\},meta:\{source:'Aghnam v7 native integration',updatedAt:new Date\(\)\.toISOString\(\)\}\};/,generic)}
if(!s.includes('function shouldReplaceLegacyDemo(')){const migration=`function shouldReplaceLegacyDemo(v){try{const d=JSON.parse(v||'null');return d?.meta?.source==='Aghnam v7 native integration'&&Array.isArray(d.sales)&&d.sales.length===8&&d.sales.every((x,i)=>x?.id===\`S-\${i+1}\`)}catch{return false}}\ntry{const current=localStorage.getItem(STORE);if(!current){const legacy=localStorage.getItem(LEGACY_STORE);localStorage.setItem(STORE,legacy&&!shouldReplaceLegacyDemo(legacy)?legacy:JSON.stringify(sample))}}catch(_){}\n`;s=s.replace('const clone=o=>JSON.parse(JSON.stringify(o));',migration+'const clone=o=>JSON.parse(JSON.stringify(o));')}
s=s.replace("a.download='aghnam-sales-v7-backup.json'","a.download='kosif-sales-backup.json'");
if(!s.includes('function parseDelimited(')){const parser=`function parseDelimited(text,sep=','){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++}else quoted=!quoted}else if(ch===sep&&!quoted){row.push(field);field=''}else if((ch==='\\n'||ch==='\\r')&&!quoted){if(ch==='\\r'&&text[i+1]==='\\n')i++;row.push(field);if(row.some(v=>String(v).trim()!==''))rows.push(row);row=[];field=''}else field+=ch}row.push(field);if(row.some(v=>String(v).trim()!==''))rows.push(row);return rows}\nfunction rowsFromDelimited(text,sep){const matrix=parseDelimited(text,sep);if(!matrix.length)return[];const hdr=matrix.shift().map(x=>String(x).trim());return matrix.map((vals,i)=>{const o={id:'IMP-'+(i+1)};hdr.forEach((h,j)=>{if(h)o[h]=String(vals[j]??'').trim()});for(const k of ['qty','revenue','cost'])o[k]=Number(String(o[k]||0).replace(/[,،]/g,''))||0;return o})}\n`;
s=s.replace("$('#importFile').onchange=async e=>{",parser+"$('#importFile').onchange=async e=>{");
s=s.replace(/else\{const sep=f\.name\.toLowerCase\(\)\.endsWith\('\.tsv'\)\?'\\t':',',[\s\S]*?return o\}\)\}/,"else{const sep=f.name.toLowerCase().endsWith('.tsv')?'\\t':',';db.sales=rowsFromDelimited(t,sep);if(!db.sales.length)throw Error('لا توجد صفوف بيانات صالحة للاستيراد')}")}
write(p,s);
const m='public/sales/sales-motion-v1.js';if(fs.existsSync(m))write(m,read(m).replace("const STORE='kosif:aghnam:v7:native';","const STORE=window.__KOSIF_SALES_STORE_KEY__||'kosif:sales:v1';"))}
function applyProfessionalCopyV46(){const b='src/v38-books.js';if(fs.existsSync(b)){let s=read(b);for(const [a,z] of [
['التواصل مع أولياء الأمور','التواصل مع المكلفين بالحوكمة'],
['التمثيلات','الإقرارات المكتوبة'],
['البيانات المكتوبة','الإقرارات المكتوبة'],
['استخدام عمل مراجعة الوظائف','استخدام عمل المراجعين الداخليين'],
['استخدام عمل المدققين الداخليين','استخدام عمل المراجعين الداخليين'],
['فقرات التأكيد والقيود في التقرير','فقرات لفت الانتباه وفقرات الأمور الأخرى في تقرير المراجع المستقل'],
['فقرات لفت الانتباه وفقرات أمور أخرى','فقرات لفت الانتباه وفقرات الأمور الأخرى في تقرير المراجع المستقل'],
['مسؤوليات المراجع عن المعلومات المصاحبة','مسؤوليات المراجع المتعلقة بالمعلومات الأخرى'],
['مسؤوليات المدقق المتعلقة بالمعلومات الأخرى','مسؤوليات المراجع المتعلقة بالمعلومات الأخرى']
])s=s.replaceAll(a,z);write(b,s)}const a='src/v38-api.js';if(fs.existsSync(a))write(a,read(a).replaceAll('لا يمكن استبدال معرّف ملاحظة موجود.','لا تُستبدل معرّفات الملاحظات القائمة بصمت؛ استخدم تعديلًا صريحًا.'))}
function applyDialogA11yV46(){const p='public/v36-voice-guide.js';if(!fs.existsSync(p))return;let s=read(p);s=s.replace('aria-labelledby="kvg-title" aria-hidden="true">','aria-labelledby="kvg-title" aria-hidden="true" inert>');s=s.replace("x.classList.add('show');x.setAttribute('aria-hidden','false');","x.inert=false;x.classList.add('show');x.setAttribute('aria-hidden','false');");s=s.replace("x.classList.remove('show');x.setAttribute('aria-hidden','true')","x.classList.remove('show');x.setAttribute('aria-hidden','true');x.inert=true");write(p,s)}
function applyServiceWorkerV46(){const p='public/sw.js';if(!fs.existsSync(p))return;let s=read(p);s=s.replace("'/suite.css'","'/bundles/kosif-suite-core-v46.css?v=46','/suite.css'").replace("'/sales/sales.css'","'/sales/sales-ui-v46.css?v=46','/sales/sales.css'").replace(",'/sales/sales-general-bootstrap.js'",'');if(!s.includes(a11yCssHref))s=s.replace("'/kosif-visual-system-v45.css?v=2026.08.21-2'",`'/kosif-visual-system-v45.css?v=2026.08.21-2','${a11yCssHref}','${a11yJsSrc}'`);write(p,s)}

let html=applyAuditCopyV46(read(source));if(!html.includes('name="kosif-design-system"'))html=html.replace('</head>','  <meta name="kosif-design-system" content="v44">\n</head>');if(!html.includes(cssHref))html=html.replace('</head>',`  <link rel="stylesheet" href="${cssHref}">\n</head>`);if(!html.includes(jsSrc))html=html.replace('</body>',`  <script src="${jsSrc}" defer></script>\n</body>`);html=applyA11yLayerV46(applyEnterpriseTokensV46(applyVisualSystemV45(html)));write(source,html);write(target,html);
for(const p of ['public/hub.html','public/libraries/index.html','public/sales/index.html','public/standards/index.html']){if(!fs.existsSync(p))continue;let s=applyAccessibilityV46(read(p),p);s=applyA11yLayerV46(applyEnterpriseTokensV46(applyVisualSystemV45(s)));write(p,s)}
for(const p of ['public/hub.html','public/libraries/index.html','public/sales/index.html'])applyShellBundleV46(p);
applySalesRuntimeV46();applyProfessionalCopyV46();applyDialogA11yV46();applyServiceWorkerV46();
const wealth='public/wealth-library-v37.js';if(fs.existsSync(wealth)){const s=read(wealth),delayed="if(initialId!=='mafateeh')setTimeout(()=>switchBook(initialId),700);",direct="if(initialId!=='mafateeh')queueMicrotask(()=>switchBook(initialId));";if(s.includes(delayed))write(wealth,s.replace(delayed,direct))}
console.log('KOSIF v46 assets ready: v44 + v45 + enterprise tokens + a11y layer + cleanup bundles + Sales migration + professional copy');
