from pathlib import Path
p=Path('public/v36-governance.js');s=p.read_text(encoding='utf-8')
s=s.replace('const KEYS={};','const KEYS={},VERIFIED={};')
for provider in ['gemini','openai','anthropic']:
    needle=f'<input id="c-model-{provider}" value="'
    i=s.find(needle)
    if i<0: continue
    end=s.find('></div>',i)
    if end<0: continue
    end+=1
    extra=f'<div style="display:flex;gap:6px;align-items:center;margin-top:7px"><button type="button" class="btn ghost sm c-test" data-p="{provider}">اختبار الاتصال</button><span class="badge mut" id="c-v-{provider}">غير مختبر</span></div>'
    if extra not in s:s=s[:end]+extra+s[end:]
anchor='function engagementDigest()'
insert=r'''function councilOK(p,m,k){const x=VERIFIED[p];return !!(x&&x.model===String(m||'').trim()&&x.key===String(k||'').trim())}
function councilState(p,text,ok=false){const x=q('#c-v-'+p);if(x){x.textContent=text;x.className='badge '+(ok?'ok':'mut')}}
function invalidateCouncil(p){delete VERIFIED[p];delete KEYS[p];councilState(p,'غير مختبر',false)}
async function testCouncilProvider(p){const status=q('#c-status');if(!window.KosifAIGate?.isUnlocked?.()){window.KosifAIGate?.open?.();return false}const key=q('#c-key-'+p)?.value.trim(),model=q('#c-model-'+p)?.value.trim();if(!key||!model){status.textContent='أدخل المفتاح والنموذج أولًا.';return false}councilState(p,'جاري الاختبار…');try{const r=await fetch('/api/kosif/ai/test',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({provider:p,model,key,agent:{jurisdiction:'saudi',industry:state?.entity?.activity||'عام'}})}),d=await r.json();if(!r.ok)throw Error(d.message||d.error||'فشل الاتصال');VERIFIED[p]={model,key,testedAt:d.testedAt||new Date().toISOString()};KEYS[p]=key;councilState(p,'متصل ✓',true);status.textContent='نجح اختبار '+p+' — أصبح مؤهلًا للمجلس في هذه الجلسة.';log('AI_PROVIDER_TESTED',{provider:p,model,testedAt:VERIFIED[p].testedAt});return true}catch(e){invalidateCouncil(p);status.textContent='فشل اختبار '+p+': '+e.message;return false}}
function bindCouncilVerification(){qa('.c-test').forEach(b=>b.onclick=()=>testCouncilProvider(b.dataset.p));for(const p of ['gemini','openai','anthropic']){q('#c-key-'+p)?.addEventListener('input',()=>invalidateCouncil(p));q('#c-model-'+p)?.addEventListener('input',()=>invalidateCouncil(p))}window.addEventListener('kosif-ai-gate-change',e=>{const on=!!e.detail?.unlocked;qa('.c-test').forEach(b=>b.disabled=!on);if(!on){for(const p of Object.keys(KEYS))delete KEYS[p];for(const p of Object.keys(VERIFIED))delete VERIFIED[p];for(const p of ['gemini','openai','anthropic'])councilState(p,'مقفول',false)}});qa('.c-test').forEach(b=>b.disabled=!window.KosifAIGate?.isUnlocked?.())}
'''
if 'function councilOK(' not in s:s=s.replace(anchor,insert+anchor)
start=s.index('async function runProvider(');end=s.index('async function runCouncil()',start)
new_provider=r'''async function runProvider(provider,model,key,task,role){const contents=[{role:'user',parts:[{text:task+'\n\nبيانات ملف الارتباط:\n'+engagementDigest()}]}];const r=await fetch('/api/kosif/ai',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({provider,model,key,contents,json:true,maxTokens:7000,agent:{jurisdiction:'saudi',industry:state?.entity?.activity||'عام',rolePrompt:role}})}),d=await r.json();if(!r.ok)throw Error(d.message||d.error||provider+' failed');return{provider,model,text:d.text,parsed:parseJson(d.text),meta:{sourceCheckedAt:d.sourceCheckedAt,standardsContextUsed:d.standardsContextUsed,booksContextUsed:d.booksContextUsed}}}
'''
s=s[:start]+new_provider+s[end:]
start=s.index('async function runCouncil()');end=s.index('function renderCouncil(',start)
new_council=r'''async function runCouncil(){const status=q('#c-status'),out=q('#c-results'),task=q('#c-task').value.trim();if(!window.KosifAIGate?.isUnlocked?.()){status.textContent='أدخل باسورد المالك أولًا.';window.KosifAIGate?.open?.();return}const all=[['gemini',q('#c-model-gemini').value.trim(),q('#c-key-gemini').value.trim()],['openai',q('#c-model-openai').value.trim(),q('#c-key-openai').value.trim()],['anthropic',q('#c-model-anthropic').value.trim(),q('#c-key-anthropic').value.trim()]].filter(x=>x[2]),cfg=all.filter(x=>councilOK(...x));if(cfg.length<2){const bad=all.filter(x=>!councilOK(...x)).map(x=>x[0]);status.textContent='المجلس يحتاج مزودين مختبرين بنجاح على الأقل.'+(bad.length?' اختبر: '+bad.join('، '):'');return}q('#c-run').disabled=true;out.innerHTML='';const reviews=[];try{for(let i=0;i<cfg.length;i++){const [p,m,k]=cfg[i];status.textContent=`تشغيل العضو ${i+1} من ${cfg.length}: ${p}…`;const role='أنت عضو مستقل في مجلس مراجعة. لا تعرف نتائج بقية الأعضاء. أعد JSON يحتوي executive_view, findings[], evidence_gaps[], proposed_adjustments[], standards_refs[], confidence, dissent_notes. كل finding يضم condition,criteria,cause,effect,risk,recommendation.';try{reviews.push(await runProvider(p,m,k,task,role))}catch(e){reviews.push({provider:p,model:m,error:e.message})}}
 let adjudication=null;const claude=cfg.find(x=>x[0]==='anthropic');if(claude){status.textContent='Claude يفصل بين الآراء ويكوّن مصفوفة الإجماع…';const evidence=reviews.map(x=>({provider:x.provider,result:x.parsed||x.error}));const chairTask='أنت رئيس مجلس المراجعين. أمامك نتائج أعضاء مستقلين. لا تفترض أن الأغلبية صحيحة تلقائياً. افصل النزاع وفق قوة الدليل والمعايير. أعد JSON: consensus_matrix[], accepted_findings[], rejected_findings[], evidence_gaps[], dissent[], chair_conclusion. صنف الإجماع 3/3 أو 2/3 أو 1/3 حيث ينطبق.\n\nنتائج الأعضاء:\n'+JSON.stringify(evidence);adjudication=await runProvider('anthropic',claude[1],claude[2],chairTask,'أنت رئيس مجلس مراجعين مهني ومحايد. افصل بناء على الدليل والمراجع لا على اسم المزود.')}
 const rec={at:new Date().toISOString(),task,providers:cfg.map(x=>x[0]),reviews:reviews.map(({provider,model,parsed,error,meta})=>({provider,model,parsed,error,meta})),adjudication:adjudication?{provider:adjudication.provider,model:adjudication.model,parsed:adjudication.parsed,meta:adjudication.meta}:null};v().councilRuns.push(rec);saveV();log('COUNCIL_RUN',{providers:rec.providers,adjudicated:!!adjudication});renderCouncil(rec);status.textContent=adjudication?'اكتمل المجلس والفصل.':'اكتملت المراجعات المستقلة؛ Claude غير مختبر/غير مشارك في الفصل.'}catch(e){status.textContent='تعذر إكمال المجلس: '+e.message}finally{q('#c-run').disabled=false}}
'''
s=s[:start]+new_council+s[end:]
s=s.replace("function init(){ensureViews();v();const run=q('#c-run');", "function init(){ensureViews();v();bindCouncilVerification();const run=q('#c-run');")
p.write_text(s,encoding='utf-8')
