(()=>{
'use strict';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const app=$('#app'), crumb=$('#crumb'), dock=$('#dock');
const STATE_KEY='std_reader_state';
const DATA='data/';
const cache=new Map();
let LIB=null, BOOK=null, CH=null, bookIndex=-1, chapterIndex=-1, searchIndex=null, searchScope='all', searchTimer=null, pendingAutoplay=false, pendingJumpQuery='', wakeLock=null;
let state={};
try{state=JSON.parse(localStorage.getItem(STATE_KEY)||'{}')}catch{state={}}
state.prefs=Object.assign({fs:19,lh:19,night:false,rate:1,autoNext:true},state.prefs||{});
state.progress=state.progress||{}; state.scroll=state.scroll||{}; state.bookmarks=state.bookmarks||[]; state.notes=state.notes||[]; state.marks=state.marks||{};

const tts={playing:false,paused:false,idx:0,els:[],utter:null};
const DIAC=/[\u064B-\u0652\u0640\u0670]/g;
const STOP=new Set(['هذا','هذه','ذلك','تلك','التي','الذي','على','الى','إلى','من','في','عن','مع','هل','ما','ماذا','كيف','اذا','إذا','كان','كانت','يكون','تكون','the','and','for','with','from','this','that','are','was','were','has','have']);
const REF_RE=/^\s*((?:\d{1,3}(?:[\/.]\d{1,3}){0,3}[أ-ي]?|\([^)]{1,10}\)|[أ-ي]\s*[\/.)]))\s*/;

function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function norm(s=''){return String(s).replace(DIAC,'').replace(/[أإآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[ؤئ]/g,'ء').replace(/[^\p{L}\p{N}]+/gu,' ').toLowerCase().trim()}
function terms(q){return [...new Set(norm(q).split(' ').filter(x=>x.length>1&&!STOP.has(x)))].slice(0,20)}
function save(){try{localStorage.setItem(STATE_KEY,JSON.stringify(state))}catch{}}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('on');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('on'),2200)}
function sourceMeta(id,year){if(id==='b3')return {label:`مرجع رسمي أحدث · ${year||2025}`,cls:'ok',weight:7};if(id==='b1')return {label:`مرجع رسمي سابق · ${year||2018}`,cls:'warn',weight:2};return {label:`مادة تدريبية · ${year||2025}`,cls:'',weight:0}}
function pagesText(p){return Array.isArray(p)&&p.length?(p[0]===p[p.length-1]?`ص ${p[0]}`:`ص ${p[0]}–${p[p.length-1]}`):''}
function route(){const h=location.hash.replace(/^#/,'');if(!h||h==='home')return {view:'home'};let m=h.match(/^book\/([^/]+)$/);if(m)return {view:'book',bookId:decodeURIComponent(m[1])};m=h.match(/^read\/([^/]+)\/(\d+)(?:\/(\d+))?$/);if(m)return {view:'read',bookId:decodeURIComponent(m[1]),chapterNo:+m[2],block:m[3]==null?null:+m[3]};return {view:'home'}}
function go(hash){if(location.hash===hash){renderRoute();return}location.hash=hash}
async function fetchJSON(path){if(cache.has(path))return cache.get(path);const p=(async()=>{const r=await fetch(path,{cache:'default'});if(!r.ok)throw Error(`تعذر تحميل ${path}`);return r.json()})();cache.set(path,p);try{return await p}catch(e){cache.delete(path);throw e}}
async function loadLibrary(){if(!LIB)LIB=await fetchJSON(DATA+'library.json');return LIB}
async function loadBook(id){const lib=await loadLibrary(), meta=lib.find(x=>x.id===id);const b=await fetchJSON(`${DATA}${id}.json`);return Object.assign({},b,{dir:b.dir||meta?.dir||'rtl',words:meta?.words||b.words||0})}
async function loadChapter(id,no){return fetchJSON(`${DATA}${id}/${no}.json`)}
function applyPrefs(){const p=state.prefs;document.body.classList.toggle('night',!!p.night);document.documentElement.style.setProperty('--fs',`${p.fs}px`);document.documentElement.style.setProperty('--lh',(p.lh/10).toFixed(1));$('#fs').value=p.fs;$('#lh').value=p.lh;$('#rate').value=p.rate;$('#autoNext').textContent=p.autoNext?'مفعّل':'متوقف';save()}
function navMode(read=false){dock.classList.toggle('on',read);$('#back').hidden=route().view==='home'}
function setLoading(){app.className='main';app.innerHTML='<div class="skeleton"></div><div class="skeleton" style="margin-top:12px"></div>'}

function bookProgress(id,chapters){const p=state.progress[id]||{};if(!chapters?.length)return 0;return Math.round(chapters.reduce((a,c)=>a+(p[c.no]||0),0)/chapters.length)}
function bookBadge(id,year){const s=sourceMeta(id,year);return `<span class="pill ${s.cls}">${esc(s.label)}</span>`}

async function renderHome(){stopSpeech();BOOK=CH=null;bookIndex=chapterIndex=-1;navMode(false);crumb.textContent='مكتبة المعايير';const lib=await loadLibrary();let cont='';if(state.last?.bookId&&state.last?.chapterNo){try{const b=await loadBook(state.last.bookId), c=b.chapters.find(x=>x.no===state.last.chapterNo);if(c)cont=`<div class="section-title"><h2>متابعة القراءة</h2></div><button class="continue-card" data-continue><div class="txt"><span class="pill">آخر قراءة</span><b>${esc(c.title)}</b><div class="mut tiny">${esc(b.title)} · ${state.progress?.[b.id]?.[c.no]||0}%</div></div><span>←</span></button>`}catch{}}
const cards=[];for(const meta of lib){let p=0;try{const b=await loadBook(meta.id);p=bookProgress(meta.id,b.chapters)}catch{}cards.push(`<button class="card" data-book="${esc(meta.id)}">${bookBadge(meta.id,meta.year)}<h3>${esc(meta.title)}</h3><div class="mut">${esc(meta.sub||'')}</div><div class="meta">${Number(meta.chapters||0).toLocaleString('ar-EG')} فصل · ${Number(meta.words||0).toLocaleString('ar-EG')} كلمة</div><div class="progress"><i style="width:${p}%"></i></div><div class="meta">التقدم ${p}%</div></button>`)}
const savedCount=state.bookmarks.length+state.notes.length;
app.className='main';app.innerHTML=`<section class="hero"><div class="chips"><span class="pill">تمحيص V2</span><span class="pill ok"><span class="status-dot ${navigator.onLine?'':'off'}"></span>${navigator.onLine?'متصل':'بدون إنترنت'}</span></div><h1>مكتبة المعايير</h1><p class="mut">قراءة وبحث واستشهاد في الكتب الثلاثة، مع أولوية واضحة لأحدث مرجع رسمي عند استخدام المكتبة داخل تمحيص.</p><div class="searchbox"><input id="homeSearch" type="search" placeholder="ابحث في كل الكتب…"><button id="homeSearchGo">⌕</button></div><div class="hero-actions"><button class="secondary" id="homeOffline">⇩ تنزيل للأوفلاين</button><button class="secondary" id="homeSaved">★ المحفوظات (${savedCount})</button></div></section>${cont}<div class="section-title"><h2>الكتب</h2><span class="mut tiny">${lib.length} كتب</span></div><div class="grid">${cards.join('')}</div>`;
$$('[data-book]').forEach(x=>x.onclick=()=>go(`#book/${x.dataset.book}`));$('[data-continue]')?.addEventListener('click',()=>go(`#read/${state.last.bookId}/${state.last.chapterNo}/${state.last.block||0}`));$('#homeSearchGo').onclick=()=>{openSheet('#searchSheet');searchScope='all';syncSearchTabs();$('#q').value=$('#homeSearch').value;performSearch()};$('#homeSearch').onkeydown=e=>{if(e.key==='Enter')$('#homeSearchGo').click()};$('#homeOffline').onclick=()=>{openSheet('#settingsSheet');setTimeout(()=>$('#offlineDownload').scrollIntoView({block:'center'}),50)};$('#homeSaved').onclick=()=>openSaved();}

async function renderBook(id){stopSpeech();const lib=await loadLibrary();BOOK=await loadBook(id);CH=null;bookIndex=lib.findIndex(x=>x.id===id);chapterIndex=-1;navMode(false);crumb.textContent=BOOK.title;const prog=state.progress[id]||{}, meta=lib[bookIndex]||BOOK;const chapters=BOOK.chapters.map((c,i)=>`<button class="chapter" data-ch="${c.no}" data-i="${i}"><span class="pill">${pagesText(c.pages)}</span><b>${esc(c.title)}</b>${c.name?`<div>${esc(c.name)}</div>`:''}<div class="meta">${Number(c.words||0).toLocaleString('ar-EG')} كلمة · التقدم ${prog[c.no]||0}%</div><div class="progress"><i style="width:${prog[c.no]||0}%"></i></div></button>`).join('');app.className='main';app.innerHTML=`<section class="hero">${bookBadge(id,meta.year)}<h1>${esc(BOOK.title)}</h1><p class="mut">${esc(BOOK.sub||'')}</p><div class="hero-actions"><button class="primary" id="bookSearch">⌕ بحث داخل الكتاب</button>${state.last?.bookId===id?'<button class="secondary" id="resumeBook">متابعة آخر قراءة</button>':''}</div></section><div class="section-title"><h2>الفصول</h2><span class="mut tiny">${BOOK.chapters.length} فصل</span></div><div class="book-list">${chapters}</div>`;$$('[data-ch]').forEach(x=>x.onclick=()=>go(`#read/${id}/${x.dataset.ch}`));$('#bookSearch').onclick=()=>{searchScope='book';openSearch()};$('#resumeBook')?.addEventListener('click',()=>go(`#read/${id}/${state.last.chapterNo}/${state.last.block||0}`));}

function extractRef(text){const m=String(text).match(REF_RE);return m?m[1]:''}
function citation(book,chapter,blockIndex,ref){const meta=sourceMeta(book.id,book.year);return `${book.title} (${book.year}) — ${chapter.title}${chapter.name?' / '+chapter.name:''}${ref?'، الفقرة '+ref:''}${chapter.pages?.length?'، '+pagesText(chapter.pages):''}${blockIndex!=null&&!ref?'، المقطع '+(blockIndex+1):''}. [${meta.label}]`}
function renderBlock(b,i,marked){const type=b?.[0], txt=String(b?.[1]||'');if(type==='h')return `<h3 data-i="${i}" data-speech="${esc(txt)}"><span class="block-text">${esc(txt)}</span></h3>`;const ref=extractRef(txt);return `<p data-i="${i}" data-speech="${esc(txt)}" class="${marked?'marked':''}"><button class="anch" data-ref="${esc(ref)}" data-bi="${i}" title="نسخ المرجع">${ref?esc(ref):'§'}</button><span class="block-text">${esc(txt)}</span></p>`}
async function renderRead(id,no,anchor){stopSpeech();const lib=await loadLibrary();BOOK=await loadBook(id);CH=await loadChapter(id,no);bookIndex=lib.findIndex(x=>x.id===id);chapterIndex=BOOK.chapters.findIndex(x=>x.no===no);navMode(true);crumb.textContent=`${BOOK.title} · ${CH.no}`;const meta=lib[bookIndex]||BOOK, key=`${id}_${no}`, marks=new Set(state.marks[key]||[]);const body=(CH.body||[]).map((b,i)=>renderBlock(b,i,marks.has(i))).join('');app.className='main reader '+(BOOK.dir==='ltr'?'ltr':'');app.innerHTML=`<header class="reader-head">${bookBadge(id,meta.year)}<h1>${esc(CH.title)}</h1>${CH.name?`<h2>${esc(CH.name)}</h2>`:''}<div class="mut tiny">${pagesText(CH.pages)} · فصل ${chapterIndex+1} من ${BOOK.chapters.length}</div><div class="reader-actions"><button id="copyChapter">نسخ المرجع</button><button id="chapterSearch">⌕ بحث هنا</button><button id="startHere">▶ اقرأ من هنا</button></div></header><article class="prose" id="prose">${body}</article>`;$('#prev').disabled=chapterIndex<=0;$('#next').disabled=chapterIndex>=BOOK.chapters.length-1;$$('.anch').forEach(a=>a.onclick=e=>{e.stopPropagation();const i=+a.dataset.bi, ref=a.dataset.ref||'';copyText(citation(Object.assign({},BOOK,{year:meta.year}),CH,i,ref));toast('تم نسخ المرجع')});$('#copyChapter').onclick=()=>{copyText(citation(Object.assign({},BOOK,{year:meta.year}),CH,null,''));toast('تم نسخ مرجع الفصل')};$('#chapterSearch').onclick=()=>{searchScope='chapter';openSearch()};$('#startHere').onclick=()=>{tts.idx=firstVisible();startSpeech(tts.idx)};state.last={bookId:id,chapterNo:no,block:anchor||0};save();requestAnimationFrame(()=>{if(anchor!=null&&$(`[data-i="${anchor}"]`))$(`[data-i="${anchor}"]`).scrollIntoView({block:'center'});else window.scrollTo(0,state.scroll[key]||0)});if(pendingJumpQuery){const qq=pendingJumpQuery;pendingJumpQuery='';setTimeout(()=>jumpToQuery(qq),80)}if(pendingAutoplay){pendingAutoplay=false;setTimeout(()=>startSpeech(0),180)}}

function blocks(){return [...document.querySelectorAll('#prose [data-i]')]}
function firstVisible(){const a=blocks();let best=0,d=Infinity;a.forEach((e,i)=>{const r=e.getBoundingClientRect(),x=Math.abs(r.top-88);if(r.bottom>72&&x<d){best=i;d=x}});return best}
let scrollTick=0;window.addEventListener('scroll',()=>{if(!CH||!BOOK)return;clearTimeout(scrollTick);scrollTick=setTimeout(()=>{const key=`${BOOK.id}_${CH.no}`,max=Math.max(1,document.documentElement.scrollHeight-innerHeight),pct=Math.max(0,Math.min(100,Math.round(scrollY/max*100))),visible=blocks()[firstVisible()];state.scroll[key]=scrollY;state.progress[BOOK.id]=state.progress[BOOK.id]||{};state.progress[BOOK.id][CH.no]=Math.max(state.progress[BOOK.id][CH.no]||0,pct);state.last={bookId:BOOK.id,chapterNo:CH.no,block:+(visible?.dataset.i||0)};save()},220)},{passive:true});

function clearVoiceMark(){document.querySelectorAll('.speaking').forEach(e=>e.classList.remove('speaking'));try{CSS.highlights?.delete('tts-word')}catch{}}
function wordRange(el,start,len){const root=el.querySelector('.block-text')||el, tw=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n,off=0,sn=null,so=0,en=null,eo=0;while(n=tw.nextNode()){const end=off+n.nodeValue.length;if(sn==null&&start>=off&&start<=end){sn=n;so=Math.max(0,start-off)}if(start+len>=off&&start+len<=end){en=n;eo=Math.max(0,start+len-off);break}off=end}if(!sn)return null;if(!en){en=sn;eo=Math.min(sn.nodeValue.length,so+len)}const r=document.createRange();r.setStart(sn,Math.min(so,sn.nodeValue.length));r.setEnd(en,Math.min(eo,en.nodeValue.length));return r}
async function lockScreen(){try{wakeLock=await navigator.wakeLock?.request('screen')}catch{}}
function unlockScreen(){try{wakeLock?.release()}catch{}wakeLock=null}
function speechText(el){return el?.dataset.speech||el?.textContent?.trim()||''}
function speakBlock(){if(!tts.playing)return;if(tts.idx>=tts.els.length){if(state.prefs.autoNext&&BOOK&&chapterIndex<BOOK.chapters.length-1){pendingAutoplay=true;const n=BOOK.chapters[chapterIndex+1];go(`#read/${BOOK.id}/${n.no}`);return}stopSpeech();return}clearVoiceMark();const el=tts.els[tts.idx],text=speechText(el).trim();if(!text){tts.idx++;speakBlock();return}el.classList.add('speaking');el.scrollIntoView({behavior:'smooth',block:'center'});state.last={bookId:BOOK.id,chapterNo:CH.no,block:+el.dataset.i};save();const u=new SpeechSynthesisUtterance(text);tts.utter=u;u.lang=BOOK?.dir==='ltr'?'en-US':'ar-SA';u.rate=Number(state.prefs.rate)||1;u.onboundary=e=>{if(e.name==='word'&&window.Highlight&&CSS.highlights){const tail=text.slice(e.charIndex),m=tail.match(/^\S+/),r=wordRange(el,e.charIndex,m?m[0].length:1);if(r)CSS.highlights.set('tts-word',new Highlight(r))}};u.onend=()=>{if(tts.playing){tts.idx++;speakBlock()}};u.onerror=e=>{if(e.error!=='canceled'){toast('تعذر تشغيل القراءة الصوتية');stopSpeech()}};speechSynthesis.speak(u);$('#speak').textContent='⏸ إيقاف مؤقت'}
function startSpeech(startIdx){if(!('speechSynthesis'in window))return toast('القراءة الصوتية غير مدعومة على هذا الجهاز');if(!CH)return;tts.els=blocks();tts.idx=startIdx==null?firstVisible():startIdx;tts.playing=true;tts.paused=false;speechSynthesis.cancel();lockScreen();speakBlock()}
function toggleSpeech(){if(tts.playing&&!tts.paused){speechSynthesis.pause();tts.paused=true;$('#speak').textContent='▶ متابعة'}else if(tts.playing&&tts.paused){speechSynthesis.resume();tts.paused=false;$('#speak').textContent='⏸ إيقاف مؤقت'}else startSpeech()}
function stopSpeech(){try{speechSynthesis.cancel()}catch{}tts.playing=tts.paused=false;tts.utter=null;clearVoiceMark();unlockScreen();if($('#speak'))$('#speak').textContent='▶ قراءة'}

async function loadSearchIndex(){if(searchIndex)return searchIndex;$('#searchStatus').textContent='جارٍ تجهيز فهرس البحث…';try{const r=await fetch(`${DATA}search-index.json.gz`,{cache:'default'});if(r.ok&&'DecompressionStream'in window){const ds=new DecompressionStream('gzip');const txt=await new Response(r.body.pipeThrough(ds)).text();searchIndex=JSON.parse(txt);return searchIndex}}catch{}return buildIndexClient()}
async function buildIndexClient(){const lib=await loadLibrary(), records=[];let done=0,total=0;const books=[];for(const m of lib){const b=await loadBook(m.id);books.push([m,b]);total+=b.chapters.length}for(const [m,b] of books){for(const c of b.chapters){try{const j=await loadChapter(m.id,c.no);records.push({book:m.id,bookTitle:m.title,year:m.year,kind:m.id==='b3'?'official-latest':m.id==='b1'?'official-legacy':'training',no:c.no,title:j.title||c.title,name:j.name||c.name||'',pages:j.pages||c.pages||[],text:(j.body||[]).map(x=>x?.[1]||'').join('\n')})}catch{}done++;if(done%8===0)$('#searchStatus').textContent=`بناء الفهرس ${done}/${total}`}}searchIndex=records;return records}
function scoreRecord(rec,q,ts){const head=norm(`${rec.title||''} ${rec.name||''}`), n=rec._n||(rec._n=norm(`${rec.title||''} ${rec.name||''} ${rec.text||''}`)),phrase=norm(q);let s=sourceMeta(rec.book,rec.year).weight,h=0;if(phrase&&n.includes(phrase))s+=45;if(phrase&&head.includes(phrase))s+=55;for(const t of ts){if(n.includes(t)){h++;s+=Math.min(12,t.length*2)}if(head.includes(t))s+=18}const ifrs=norm(q).match(/(?:ifrs|المعيار الدولي للتقرير المالي)\s*(\d+)/),ias=norm(q).match(/(?:ias|المعيار الدولي للمحاسبه)\s*(\d+)/);if(ifrs&&head.includes(norm('المعيار الدولي للتقرير المالي '+ifrs[1])))s+=120;if(ias&&head.includes(norm('المعيار الدولي للمحاسبه '+ias[1])))s+=120;return h||phrase&&n.includes(phrase)?s:-1}
function rawSnippet(text,q,ts){text=String(text||'').replace(/\s+/g,' ');let pos=-1;for(const t of [q,...ts]){if(!t)continue;const p=text.toLowerCase().indexOf(String(t).toLowerCase());if(p>=0&&(pos<0||p<pos))pos=p}if(pos<0)pos=0;const st=Math.max(0,pos-140), out=(st?'…':'')+text.slice(st,st+430)+(st+430<text.length?'…':'');return out}
function highlight(text,ts){let out=esc(text);for(const t of ts.filter(x=>x.length>1).slice(0,8)){const safe=t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');try{out=out.replace(new RegExp(`(${safe})`,'gi'),'<mark>$1</mark>')}catch{}}return out}
async function performSearch(){const q=$('#q').value.trim();if(q.length<2){$('#results').innerHTML='';$('#searchStatus').textContent='اكتب حرفين على الأقل.';return}const ts=terms(q);$('#searchStatus').textContent='جارٍ البحث…';let records=[];if(searchScope==='chapter'&&CH&&BOOK){records=[{book:BOOK.id,bookTitle:BOOK.title,year:(await loadLibrary()).find(x=>x.id===BOOK.id)?.year||BOOK.year,no:CH.no,title:CH.title,name:CH.name||'',pages:CH.pages||[],text:(CH.body||[]).map(x=>x?.[1]||'').join('\n')}]}else{records=await loadSearchIndex();if(searchScope==='book'&&BOOK)records=records.filter(r=>r.book===BOOK.id)}const hits=[];for(const r of records){const s=scoreRecord(r,q,ts);if(s>=0)hits.push([s,r])}hits.sort((a,b)=>b[0]-a[0]);const top=hits.slice(0,60);$('#searchStatus').textContent=top.length?`${top.length} نتيجة${hits.length>60?' من نتائج أكثر':''}`:'لا توجد نتائج.';$('#results').innerHTML=top.map(([s,r],i)=>{const sn=rawSnippet(r.text,q,ts), sm=sourceMeta(r.book,r.year);return `<button class="result" data-r="${i}"><span class="pill ${sm.cls}">${esc(sm.label)}</span><b>${esc(r.title)}</b>${r.name?`<div>${esc(r.name)}</div>`:''}<div class="mut tiny">${esc(r.bookTitle||'')} · ${pagesText(r.pages)}</div><div class="mut" style="margin-top:7px">${highlight(sn,[q,...ts])}</div></button>`}).join('');$$('[data-r]').forEach(x=>x.onclick=()=>{const r=top[+x.dataset.r][1];closeSheets();pendingJumpQuery=q;go(`#read/${r.book}/${r.no}`)})}
function jumpToQuery(q){if(!CH)return;const nq=norm(q),ts=terms(q);let idx=-1;for(let i=0;i<CH.body.length;i++){const n=norm(CH.body[i]?.[1]||'');if(nq&&n.includes(nq)||ts.some(t=>n.includes(t))){idx=i;break}}if(idx>=0)$(`[data-i="${idx}"]`)?.scrollIntoView({behavior:'smooth',block:'center'})}
function syncSearchTabs(){$$('#searchTabs button').forEach(b=>{b.classList.toggle('on',b.dataset.scope===searchScope);b.disabled=(b.dataset.scope==='book'&&!BOOK)||(b.dataset.scope==='chapter'&&!CH)})}
function openSearch(){openSheet('#searchSheet');syncSearchTabs();setTimeout(()=>$('#q').focus(),80);if($('#q').value.trim().length>=2)performSearch()}

function copyText(s){if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(s).catch(()=>fallbackCopy(s));fallbackCopy(s)}
function fallbackCopy(s){const t=document.createElement('textarea');t.value=s;document.body.appendChild(t);t.select();try{document.execCommand('copy')}catch{}t.remove()}
function openSaved(){const items=[];state.bookmarks.slice().reverse().forEach((x,i)=>items.push({type:'bookmark',x,i}));state.notes.slice().reverse().forEach((x,i)=>items.push({type:'note',x,i}));$('#savedBody').innerHTML=items.length?items.map((o,i)=>{const x=o.x;return `<button class="saved-item" data-si="${i}"><span class="pill">${o.type==='note'?'ملاحظة':'علامة'}</span><b>${esc(x.chapterTitle||x.chapter||'محفوظ')}</b><div class="mut">${esc((x.text||x.bookTitle||'').slice(0,260))}</div><div class="tiny mut">${x.time?new Date(x.time).toLocaleString('ar-EG'):''}</div></button>`}).join(''):'<div class="empty">لا توجد محفوظات بعد.</div>';$$('[data-si]').forEach(b=>b.onclick=()=>{const o=items[+b.dataset.si],x=o.x;if(x.bookId&&x.chapterNo){closeSheets();go(`#read/${x.bookId}/${x.chapterNo}/${x.block||0}`)}});openSheet('#savedSheet')}
function saveSelection(){if(!CH||!BOOK)return;const sel=getSelection(),txt=sel?.toString().trim();if(!txt)return toast('حدّد نصًا أولاً');let n=sel.anchorNode;while(n&&n.nodeType!==1)n=n.parentNode;const el=n?.closest('[data-i]');if(!el)return toast('تعذر تحديد موضع النص');const i=+el.dataset.i,key=`${BOOK.id}_${CH.no}`,ref=extractRef(CH.body[i]?.[1]||'');state.notes.push({bookId:BOOK.id,bookTitle:BOOK.title,chapterNo:CH.no,chapterTitle:CH.title,block:i,ref,text:txt.slice(0,1200),time:Date.now()});state.marks[key]=state.marks[key]||[];if(!state.marks[key].includes(i))state.marks[key].push(i);el.classList.add('marked');save();sel.removeAllRanges();toast('تم حفظ الملاحظة والتظليل')}
function addBookmark(){if(!CH||!BOOK)return;const el=blocks()[firstVisible()],i=+(el?.dataset.i||0),ref=extractRef(CH.body[i]?.[1]||'');state.bookmarks.push({bookId:BOOK.id,bookTitle:BOOK.title,chapterNo:CH.no,chapterTitle:CH.title,block:i,ref,time:Date.now()});save();toast('تمت إضافة علامة القراءة')}

async function downloadOffline(){const btn=$('#offlineDownload'),bar=$('#offlineProgress'),fill=bar.querySelector('i'),txt=$('#offlineText');btn.disabled=true;bar.hidden=false;txt.textContent='جارٍ إعداد قائمة الملفات…';try{const lib=await loadLibrary(),urls=['./','./index.html','./styles.css','./app.js','./data/library.json','./data/search-index.json.gz','../','../index.html','../manifest.webmanifest','../sw.js'];for(const m of lib){const b=await loadBook(m.id);urls.push(`./data/${m.id}.json`);for(const c of b.chapters)urls.push(`./data/${m.id}/${c.no}.json`)}const c=await caches.open('tamhees-offline-v2'),unique=[...new Set(urls)],total=unique.length;let done=0,failed=0,cursor=0;async function worker(){while(cursor<total){const i=cursor++,u=unique[i];try{const r=await fetch(u,{cache:'reload'});if(r.ok)await c.put(u,r.clone());else failed++}catch{failed++}done++;fill.style.width=`${Math.round(done/total*100)}%`;if(done%8===0||done===total)txt.textContent=`${done}/${total} ملف${failed?` · تعذر ${failed}`:''}`}}await Promise.all(Array.from({length:6},worker));state.offlineReady=failed===0;save();toast(failed?'اكتمل التنزيل مع بعض الملفات المتعذرة':'المكتبة جاهزة للعمل بدون إنترنت');txt.textContent=failed?`تم حفظ ${total-failed} من ${total} ملف.`:`تم حفظ ${total} ملفًا على الجهاز.`}catch(e){txt.textContent='تعذر تنزيل المكتبة كاملة.';toast(e.message||'تعذر التنزيل')}finally{btn.disabled=false}}

function openSheet(id){$('#shade').classList.add('on');$(id).classList.add('on')}
function closeSheets(){$('#shade').classList.remove('on');$$('.sheet').forEach(x=>x.classList.remove('on'))}
function goBack(){const r=route();if(r.view==='read')go(`#book/${r.bookId}`);else if(r.view==='book')go('#home');else history.back()}

async function renderRoute(){setLoading();applyPrefs();const r=route();try{if(r.view==='book')await renderBook(r.bookId);else if(r.view==='read')await renderRead(r.bookId,r.chapterNo,r.block);else await renderHome()}catch(e){console.error(e);app.className='main';app.innerHTML=`<div class="empty"><h2>تعذر فتح المكتبة</h2><p>${esc(e.message||e)}</p><button class="primary" id="retry">إعادة المحاولة</button></div>`;$('#retry').onclick=()=>{cache.clear();renderRoute()}}}

$('#shade').onclick=closeSheets;$('#prefsBtn').onclick=()=>openSheet('#settingsSheet');$('#searchBtn').onclick=()=>{searchScope=route().view==='read'?'chapter':route().view==='book'?'book':'all';openSearch()};$('#savedBtn').onclick=openSaved;$('#back').onclick=goBack;$('#theme').onclick=()=>{state.prefs.night=!state.prefs.night;applyPrefs()};$('#fs').oninput=e=>{state.prefs.fs=+e.target.value;applyPrefs()};$('#lh').oninput=e=>{state.prefs.lh=+e.target.value;applyPrefs()};$('#rate').oninput=e=>{state.prefs.rate=+e.target.value;save();if(tts.playing){const idx=tts.idx;stopSpeech();startSpeech(idx)}};$('#autoNext').onclick=()=>{state.prefs.autoNext=!state.prefs.autoNext;applyPrefs()};$('#stopVoice').onclick=stopSpeech;$('#resetState').onclick=()=>{if(confirm('مسح التقدم والملاحظات والعلامات من هذا الجهاز؟')){const p=state.prefs;state={prefs:p,progress:{},scroll:{},bookmarks:[],notes:[],marks:{}};save();closeSheets();renderRoute();toast('تم مسح البيانات المحلية')}};$('#offlineDownload').onclick=downloadOffline;$('#prev').onclick=()=>{if(BOOK&&chapterIndex>0)go(`#read/${BOOK.id}/${BOOK.chapters[chapterIndex-1].no}`)};$('#next').onclick=()=>{if(BOOK&&chapterIndex<BOOK.chapters.length-1)go(`#read/${BOOK.id}/${BOOK.chapters[chapterIndex+1].no}`)};$('#speak').onclick=toggleSpeech;$('#note').onclick=saveSelection;$('#bookmark').onclick=addBookmark;$('#q').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(performSearch,260)});$('#q').addEventListener('keydown',e=>{if(e.key==='Enter'){clearTimeout(searchTimer);performSearch()}});$$('#searchTabs button').forEach(b=>b.onclick=()=>{searchScope=b.dataset.scope;syncSearchTabs();performSearch()});window.addEventListener('hashchange',renderRoute);window.addEventListener('online',()=>toast('تم استعادة الاتصال'));window.addEventListener('offline',()=>toast('أنت الآن بدون إنترنت'));

document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&tts.playing)lockScreen()});
applyPrefs();renderRoute();
})();
