(()=>{
'use strict';
const DB_NAME='tamhees-standards-v1', STORE='files';
const POLICY=`\n\n[سياسة مراجع مكتبة المعايير]\n- مكتبة المعايير المحلية مصدر داعم للفهم والاستدلال والاستشهاد، وليست دليلاً تلقائياً على أن نصاً قديماً ما زال نافذاً.\n- عند أي مسألة قد تتأثر بتحديث معياري أو تنظيمي: تحقّق من أحدث مصدر رسمي متاح على الإنترنت. أعطِ الأولوية لمؤسسة IFRS/IASB والهيئة السعودية للمراجعين والمحاسبين SOCPA والجهات النظامية الرسمية ذات الصلة.\n- إذا تعارض نص محلي أقدم مع إصدار رسمي أحدث، قدّم الحكم الأحدث، واذكر بوضوح أن النسخة الأقدم كانت تنص على كذا مع بيان الفرق أو تاريخ/إصدار التغيير متى أمكن.\n- ميّز دائماً بين: نص معياري رسمي، تفسير/مادة تدريبية، واستنتاج مهني. لا تنسب للمصدر ما لم يرد فيه.\n- كتاب ACCA/BPP مادة تدريبية مساندة وليس مصدراً معيارياً أعلى من نصوص IFRS/IASB أو الاعتمادات الرسمية السعودية.\n`;
const ACRE=/[أإآٱ]/g, DIAC=/[\u064B-\u0652\u0640\u0670]/g;
function norm(s=''){return String(s).replace(DIAC,'').replace(ACRE,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[ؤئ]/g,'ء').replace(/[^\p{L}\p{N}]+/gu,' ').toLowerCase().trim()}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function getAllFiles(){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),st=tx.objectStore(STORE),r=st.openCursor(),out=[];r.onsuccess=()=>{const c=r.result;if(!c)return resolve(out);out.push([String(c.key),c.value]);c.continue()};r.onerror=()=>reject(r.error)})}
let docsP=null;
async function docs(){if(docsP)return docsP;docsP=(async()=>{const rows=await getAllFiles(), out=[];for(const [k,v] of rows){if(!/^data\/b[123]\/\d+\.json$/.test(k))continue;try{const j=typeof v==='string'?JSON.parse(v):JSON.parse(new TextDecoder().decode(v));const text=(j.body||[]).map(x=>x&&x[1]||'').join('\n');if(text.trim())out.push({path:k,no:j.no,title:j.title||'',name:j.name||'',pages:j.pages||[],text,n:norm(text)})}catch{}}return out})();return docsP}
function extractQuery(payload){if(!payload||typeof payload!=='object')return'';if(typeof payload.input==='string')return payload.input;let a=[];for(const c of payload.contents||[]){for(const p of c.parts||[]){if(typeof p.text==='string')a.push(p.text)}}return a.join('\n')}
function terms(q){const stop=new Set(['هذا','هذه','ذلك','التي','الذي','على','الى','إلى','من','في','عن','مع','هل','ما','ماذا','كيف','اذا','إذا','the','and','for','with','from','this','that']);return [...new Set(norm(q).split(' ').filter(x=>x.length>1&&!stop.has(x)))].slice(-24)}
function snippet(text,ts){const n=norm(text);let pos=-1;for(const t of ts){const p=n.indexOf(t);if(p>=0&&(pos<0||p<pos))pos=p}if(pos<0)return text.slice(0,1200);const approx=Math.max(0,pos-300);return text.slice(approx,approx+1500)}
async function search(q,limit=6){const ts=terms(q);if(!ts.length)return[];const all=await docs(), scored=[];for(const d of all){let s=0,h=0;for(const t of ts){const p=d.n.indexOf(t);if(p>=0){h++;s+=t.length>=5?5:2;const second=d.n.indexOf(t,p+1);if(second>=0)s+=1}}if(/ifrs\s*\d+/i.test(q)){const m=q.match(/ifrs\s*(\d+)/i);if(m&&norm(d.title+' '+d.name).includes(norm('ifrs '+m[1])))s+=25}if(/ias\s*\d+/i.test(q)){const m=q.match(/ias\s*(\d+)/i);if(m&&norm(d.title+' '+d.name).includes(norm('ias '+m[1])))s+=25}if(h>=Math.min(2,ts.length))scored.push([s,d])}scored.sort((a,b)=>b[0]-a[0]);return scored.slice(0,limit).map(([score,d])=>({score,...d,snippet:snippet(d.text,ts)}))}
function localContext(items){if(!items.length)return'';return '\n\n[مقتطفات داعمة من مكتبة المعايير المحلية — يجب التحقق من الحداثة قبل اعتماد الحكم النهائي]\n'+items.map((x,i)=>`${i+1}) ${x.title}${x.name?' — '+x.name:''} | ${x.path}${x.pages?.length?' | صفحات '+x.pages.join('–'):''}\n${x.snippet}`).join('\n\n')}
function appendSystem(payload,text){if(typeof payload.systemInstruction==='string')payload.systemInstruction+=text;else if(payload.systemInstruction?.parts){payload.systemInstruction.parts.push({text})}else if(typeof payload.system_instruction==='string')payload.system_instruction+=text;else payload.systemInstruction=text}
function addGoogleSearch(payload){if(!Array.isArray(payload.tools))payload.tools=[];const has=payload.tools.some(t=>t&&(t.google_search||t.googleSearch));if(!has)payload.tools.push({google_search:{}})}
async function augment(payload,direct){const q=extractQuery(payload);if(!q||q.length<20)return payload;let items=[];try{items=await search(q,6)}catch{}appendSystem(payload,POLICY+localContext(items));if(direct)addGoogleSearch(payload);return payload}
const realFetch=window.fetch.bind(window);
window.fetch=async function(input,init){try{const url=typeof input==='string'?input:(input?.url||String(input));const isDirect=/generativelanguage\.googleapis\.com/i.test(url);const isProxy=/\/api\/gemini-proxy(?:\?|$)/i.test(url);if((isDirect||isProxy)&&init&&typeof init.body==='string'&&/json/i.test((init.headers&&((init.headers['Content-Type']||init.headers['content-type'])||''))||'application/json')){const p=JSON.parse(init.body);await augment(p,isDirect);init={...init,body:JSON.stringify(p)}}}catch(e){console.warn('standards bridge skipped',e)}return realFetch(input,init)};
window.TamheesStandards={search,policy:POLICY,reload(){docsP=null;return docs()}};
function addButton(){if(document.getElementById('tamhees-standards-button'))return;const a=document.createElement('a');a.id='tamhees-standards-button';a.href='./standards/';a.textContent='📚 مكتبة المعايير';a.title='فتح مكتبة المعايير';Object.assign(a.style,{position:'fixed',left:'14px',bottom:'calc(14px + env(safe-area-inset-bottom))',zIndex:'2147483000',padding:'10px 14px',borderRadius:'999px',background:'#16232C',color:'#fff',font:'600 13px system-ui',textDecoration:'none',boxShadow:'0 8px 25px #0003'});document.body.appendChild(a)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addButton,{once:true});else addButton();
})();