(()=>{
'use strict';
const VERSION='2.0.0';
const INDEX='./standards/data/search-index.json.gz';
const POLICY=`\n\n[سياسة مراجع تمحيص]\n- استخدم مكتبة المعايير المحلية كمصدر داعم للفهم والاستدلال والاستشهاد، ولا تفترض أن كل نص محفوظ فيها هو الحكم النافذ اليوم.\n- عند مسألة معيارية أو تنظيمية قد تتغير بمرور الوقت، تحقّق من أحدث مصدر رسمي متاح على الإنترنت. الأولوية لمؤسسة IFRS/IASB، ثم SOCPA والجهات النظامية الرسمية ذات الصلة.\n- إذا تعارض نص أقدم في المكتبة مع إصدار رسمي أحدث، قدّم الحكم الأحدث، ثم اذكر بإيجاز ما كان يقوله النص الأقدم وما الذي تغير.\n- فرّق صراحة بين: (1) نص معياري رسمي، (2) ترجمة/إصدار رسمي أقدم، (3) مادة تدريبية ACCA/BPP، (4) استنتاج مهني.\n- لا تنسب للمصدر نصاً أو حكماً غير موجود فيه، ولا تجعل مادة تدريبية أعلى في القوة المرجعية من النص المعياري الرسمي.\n`;
const DIAC=/[\u064B-\u0652\u0640\u0670]/g, STOP=new Set(['هذا','هذه','ذلك','التي','الذي','على','الى','إلى','من','في','عن','مع','هل','ما','ماذا','كيف','اذا','إذا','the','and','for','with','from','this','that']);
let indexP=null;
function norm(s=''){return String(s).replace(DIAC,'').replace(/[أإآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[ؤئ]/g,'ء').replace(/[^\p{L}\p{N}]+/gu,' ').toLowerCase().trim()}
function terms(q){return [...new Set(norm(q).split(' ').filter(x=>x.length>1&&!STOP.has(x)))].slice(0,22)}
function source(r){return r.book==='b3'?{label:'مرجع رسمي أحدث',w:9}:r.book==='b1'?{label:'مرجع رسمي سابق',w:3}:{label:'مادة تدريبية ACCA/BPP',w:0}}
async function loadIndex(){if(indexP)return indexP;indexP=(async()=>{const r=await fetch(INDEX,{cache:'default'});if(!r.ok)throw Error('standards index unavailable');if(!('DecompressionStream'in window))throw Error('gzip unsupported');const ds=new DecompressionStream('gzip'),txt=await new Response(r.body.pipeThrough(ds)).text();return JSON.parse(txt)})();return indexP}
function score(r,q,ts){const head=norm(`${r.title||''} ${r.name||''}`), n=r._n||(r._n=norm(`${r.title||''} ${r.name||''} ${r.text||''}`)),phrase=norm(q);let s=source(r).w,h=0;if(phrase&&n.includes(phrase))s+=35;if(phrase&&head.includes(phrase))s+=55;for(const t of ts){if(n.includes(t)){h++;s+=Math.min(10,t.length*2)}if(head.includes(t))s+=16}const ifrs=phrase.match(/(?:ifrs|المعيار الدولي للتقرير المالي)\s*(\d+)/),ias=phrase.match(/(?:ias|المعيار الدولي للمحاسبه)\s*(\d+)/);if(ifrs&&head.includes(norm('المعيار الدولي للتقرير المالي '+ifrs[1])))s+=130;if(ias&&head.includes(norm('المعيار الدولي للمحاسبه '+ias[1])))s+=130;return h||phrase&&n.includes(phrase)?s:-1}
function snippet(text,ts){text=String(text||'').replace(/\s+/g,' ');let pos=-1;for(const t of ts){const p=text.toLowerCase().indexOf(String(t).toLowerCase());if(p>=0&&(pos<0||p<pos))pos=p}if(pos<0)pos=0;const st=Math.max(0,pos-260);return (st?'…':'')+text.slice(st,st+1500)+(st+1500<text.length?'…':'')}
async function search(q,limit=5){const ts=terms(q);if(!ts.length)return[];let rows=[];try{rows=await loadIndex()}catch{return []}const hits=[];for(const r of rows){const s=score(r,q,ts);if(s>=0)hits.push([s,r])}hits.sort((a,b)=>b[0]-a[0]);return hits.slice(0,limit).map(([score,r])=>({score,...r,source:source(r).label,snippet:snippet(r.text,[q,...ts])}))}
function extractQuery(payload){if(!payload||typeof payload!=='object')return'';if(typeof payload.input==='string')return payload.input;const out=[];for(const c of payload.contents||[])for(const p of c.parts||[])if(typeof p.text==='string')out.push(p.text);return out.join('\n')}
function appendSystem(payload,text){if(typeof payload.systemInstruction==='string')payload.systemInstruction+=text;else if(payload.systemInstruction?.parts)payload.systemInstruction.parts.push({text});else if(typeof payload.system_instruction==='string')payload.system_instruction+=text;else payload.systemInstruction={parts:[{text}]}}
function addGoogleSearch(payload){if(!Array.isArray(payload.tools))payload.tools=[];if(!payload.tools.some(t=>t&&(t.google_search||t.googleSearch)))payload.tools.push({google_search:{}})}
function localContext(items){if(!items.length)return'';return '\n\n[مراجع محلية مطابقة من مكتبة تمحيص — افحص الحداثة قبل الحكم النهائي]\n'+items.map((x,i)=>`${i+1}) ${x.source} | ${x.bookTitle||''} (${x.year||''}) | ${x.title}${x.name?' — '+x.name:''}${x.pages?.length?' | الصفحات '+x.pages.join('–'):''}\n${x.snippet}`).join('\n\n')}
function isAccounting(q){return /(معيار|محاسب|مراجع|قوائم مالي|افصاح|إفصاح|اثبات|إثبات|قياس|ايراد|إيراد|اصل|أصل|التزام|ifrs|ias|acca|audit|account|financial statement|revenue|impairment|lease|inventory|provision|fair value)/i.test(q)}
async function augment(payload,direct){const q=extractQuery(payload);if(!q||q.length<8)return payload;let items=[];try{items=await search(q,5)}catch{}if(items.length||isAccounting(q)){appendSystem(payload,POLICY+localContext(items));if(direct)addGoogleSearch(payload)}return payload}
const realFetch=window.fetch.bind(window);
window.fetch=async function(input,init){try{const url=typeof input==='string'?input:(input?.url||String(input)),direct=/generativelanguage\.googleapis\.com/i.test(url),proxy=/\/api\/gemini-proxy(?:\?|$)/i.test(url);if((direct||proxy)&&init&&typeof init.body==='string'){const p=JSON.parse(init.body);await augment(p,direct);init={...init,body:JSON.stringify(p)}}}catch(e){console.warn('Tamhees standards bridge:',e)}return realFetch(input,init)};
window.TamheesStandards={version:VERSION,search,policy:POLICY,reload(){indexP=null;return loadIndex()}};
})();
