(()=>{
'use strict';
const READER='./standards/';
function goReader(e){if(e){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation?.()}location.href=READER}
function addQuickButton(){if(document.getElementById('tamhees-library-quick'))return;const a=document.createElement('a');a.id='tamhees-library-quick';a.href=READER;a.innerHTML='<span aria-hidden="true">📚</span> المعايير';a.title='فتح مكتبة المعايير';a.style.cssText='position:fixed;left:12px;bottom:calc(76px + env(safe-area-inset-bottom));z-index:2147483000;padding:10px 13px;border-radius:999px;background:#162b37;color:#fff;text-decoration:none;font:700 13px system-ui;box-shadow:0 8px 26px #0003;border:1px solid #ffffff22';document.body.appendChild(a)}
function addLibraryEntry(){const view=document.querySelector('#view-library');if(!view||document.getElementById('full-standards-reader-entry'))return;const box=document.createElement('section');box.id='full-standards-reader-entry';box.style.cssText='margin:0 0 14px;padding:16px;border:1px solid #d8c69d;border-radius:15px;background:#fffaf0;display:flex;gap:12px;align-items:center;justify-content:space-between;flex-wrap:wrap';box.innerHTML='<div><b style="display:block;font-size:16px;margin-bottom:5px">مكتبة المعايير V2 — 3 كتب</b><span style="font-size:13px;opacity:.78">بحث شامل، قراءة صوتية، مراجع، تقدم، ملاحظات وعمل بدون إنترنت.</span></div><a href="./standards/" style="text-decoration:none;padding:10px 14px;border-radius:10px;background:#162b37;color:#fff;font-weight:800">فتح المكتبة</a>';view.prepend(box)}
function wire(){document.querySelectorAll('[data-go="library"]').forEach(el=>{if(el.dataset.fullReaderWired)return;el.dataset.fullReaderWired='1';el.addEventListener('click',goReader,true)});addQuickButton();addLibraryEntry()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire,{once:true});else wire();new MutationObserver(wire).observe(document.documentElement,{childList:true,subtree:true});
})();
