-- KOSIF System Brain v2 — PostgreSQL + pgvector semantic memory
-- Service-role only. No browser key is permitted to read or mutate this knowledge store.

create extension if not exists vector with schema extensions;
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.kosif_brain_documents (
  id uuid primary key default extensions.gen_random_uuid(),
  document_key text not null unique,
  title text not null,
  source_type text not null default 'uploaded-pdf',
  source_ref text,
  authority text not null default 'reference',
  jurisdiction text not null default 'saudi',
  period_label text,
  content_sha256 text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint kosif_brain_document_key_len check (char_length(document_key) between 1 and 180),
  constraint kosif_brain_title_len check (char_length(title) between 1 and 300)
);

create table if not exists public.kosif_brain_chunks (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.kosif_brain_documents(id) on delete cascade,
  chunk_index integer not null,
  page_start integer,
  page_end integer,
  content text not null,
  embedding extensions.vector(1536) not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint kosif_brain_chunk_index_nonnegative check (chunk_index >= 0),
  constraint kosif_brain_chunk_content_nonempty check (char_length(content) >= 1),
  constraint kosif_brain_page_range check (page_start is null or page_end is null or page_end >= page_start),
  unique(document_id, chunk_index)
);

create index if not exists kosif_brain_documents_updated_idx
  on public.kosif_brain_documents(updated_at desc);
create index if not exists kosif_brain_documents_jurisdiction_idx
  on public.kosif_brain_documents(jurisdiction, authority);
create index if not exists kosif_brain_chunks_document_idx
  on public.kosif_brain_chunks(document_id, chunk_index);
create index if not exists kosif_brain_chunks_fts_idx
  on public.kosif_brain_chunks using gin (to_tsvector('simple', content));
create index if not exists kosif_brain_chunks_embedding_hnsw_idx
  on public.kosif_brain_chunks using hnsw (embedding extensions.vector_cosine_ops);

alter table public.kosif_brain_documents enable row level security;
alter table public.kosif_brain_chunks enable row level security;

-- Intentionally no anon/authenticated RLS policies: only the server-side service role can access the store.
revoke all on table public.kosif_brain_documents from anon, authenticated;
revoke all on table public.kosif_brain_chunks from anon, authenticated;
revoke all on sequence public.kosif_brain_chunks_id_seq from anon, authenticated;
grant all on table public.kosif_brain_documents to service_role;
grant all on table public.kosif_brain_chunks to service_role;
grant usage, select on sequence public.kosif_brain_chunks_id_seq to service_role;

create or replace function public.kosif_match_brain_chunks(
  query_embedding extensions.vector(1536),
  match_count integer default 8,
  filter_document_key text default null
)
returns table (
  chunk_id bigint,
  document_id uuid,
  document_key text,
  title text,
  source_type text,
  authority text,
  jurisdiction text,
  period_label text,
  page_start integer,
  page_end integer,
  content text,
  metadata jsonb,
  similarity double precision
)
language sql
stable
set search_path = public, extensions
as $$
  select
    c.id as chunk_id,
    d.id as document_id,
    d.document_key,
    d.title,
    d.source_type,
    d.authority,
    d.jurisdiction,
    d.period_label,
    c.page_start,
    c.page_end,
    c.content,
    c.metadata,
    (1 - (c.embedding <=> query_embedding))::double precision as similarity
  from public.kosif_brain_chunks c
  join public.kosif_brain_documents d on d.id = c.document_id
  where filter_document_key is null or d.document_key = filter_document_key
  order by c.embedding <=> query_embedding
  limit least(greatest(coalesce(match_count, 8), 1), 20);
$$;

revoke all on function public.kosif_match_brain_chunks(extensions.vector, integer, text) from public, anon, authenticated;
grant execute on function public.kosif_match_brain_chunks(extensions.vector, integer, text) to service_role;

comment on table public.kosif_brain_documents is 'KOSIF System Brain v2 source documents with provenance.';
comment on table public.kosif_brain_chunks is 'KOSIF System Brain v2 page-aware semantic chunks. 1536-d embeddings.';
comment on function public.kosif_match_brain_chunks is 'Service-role semantic retrieval for KOSIF; cosine similarity, maximum 20 results.';
